### PR TITLE
fix: Treats mcc and mnc as text instead of numbers

### LINKED ISSUE #196: Mobile Country Code starting with zeros are not accepted in the network slice creation modal
#### Describe the bug
Mobile Country Code starting with zeros are not accepted in the network slice creation modal. Examples: `001`, `012`.

#### To Reproduce

1. Create a Network Slice with a MCC of `001`

#### Expected behavior

MCC's starting with zeros are accepted.

#### Screenshots

image

### PR DESCRIPTION
**Pull request by gruyaume**
# Description

The network slice creation modal use to consider MCC's and MNC's starting with zero's as invalid. This PR fixes this problem by considering those entries as text instead of numbers.

Fixes #196 

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that validate the behaviour of the software.
- [ ] I validated that new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by gatici — APPROVED** [review]

**Comment by gruyaume** [comment]
> i don't see any validation about the characters that can be used over the mcc and mnc. What happens if we make mcc=abc ?

Agreed, fixed

File: components/CreateNetworkSliceModal.tsx [hunk 1]
```diff
@@ -26,22 +27,38 @@ interface NetworkSliceModalProps {
...
+        message: "Only alphanumeric characters, dashes and underscores.",
+      })
       .required("Name is required."),
-    mcc: Yup.string().length(3).required("MCC must be exactly 3 digits"),
-    mnc: Yup.string().min(2).max(3).required("MNC must be 2 or 3 digits"),
-    upf: Yup.object().shape({hostname: Yup.string().required("Please select a UPF")}).required("Please select a UPF."),
-    gnbList: Yup.array().min(1).required("Please select at least one gNodeB."),
+    mcc: Yup.string()
+      .matches(
+        /^(00[1-9]|0[1-9]\d|[1-9]\d\d)$/,
```
Comment (patriciareinoso) [inline components/CreateNetworkSliceModal.tsx:46]: why not /^\d{3}$/ ?
